language: java
jdk: openjdk8
sudo: false
env:
  global:
  - secure: "broqXw5X7BrQ86HTpPNi119PYyG7PaHNnpjcUJsemcsaYFkJc1Tt7s9KF/hIq+AQqV300V2mDnXiIXnQEO+gU7Iexs88ZFPXESOfx8wFC0IFz+Lfp73PQrhKWZMXf27KPVatF5IXhswaZo/k1LYeVpnk0nikQW2FU6yBaYO1TM0="
  - secure: "KjrmAJP5fc5RUUY9ntz8VxrfzmUwBOJFbkj+UM/aGJ+Rqkvlbm4/97j9Ujgzxl7QZXxnjDqd79WLgrJnCiZJfJosCyVtUDOrD0L9iy/C5NDiDciOdKD7180d5rxFCKCoXNUKKD0OusOxmcfAggZkdMsuGjAzS7LiEWPtZGHEu+k="
  - secure: "T9cF53iyzWcdxTaDrqbGdYCKcx220CefsgpvuTzpCHKeirrCeIqhi1gBecJdtmyY5Si+odRRXOcnVwogenBLCuglfQPOlWSlu1tnLgGu5GwuNlHjQYBfLQfwi+CVnKPWYGK6N/Cgo4op2GJyISDkLhQB3ik0F1x99H2NWR8OM9w="
  - secure: "KcysTDLW6AYfwJBVj/bnr5s/52aP3e6veU8UZG7C6zUoJTQ/SFoVKpzL8hYAbDmj92ueRXq8WwZ0/LgpyJiCJgaR/JiT+C9Pv0JDAQuDk653oaHygqKk7B5XyakzwSszeYKiI+T1RRaupVzgFqvcocfPNX9KHv3q95r64sDP+48="
install: /bin/true
script:
  - export BRANCH_NAME=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - ./ci/script/build.sh
#  - ./ci/script/run_integrated_tests.sh
after_success:
  - ./ci/script/deploy.sh
cache:
  directories:
    - $HOME/.gradle
